name: foodeasecakes
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.20.0-nullsafety.3
  cached_network_image:
  flutter_bloc: ^8.1.3
  sqflite: 
  equatable: 
  # firebase_messaging: 
  bloc: 
  flutter_launcher_icons: ^0.10.0
  image_picker: ^0.8.4+11
  http: ^0.13.4
  fluttertoast: ^8.1.2
  in_app_purchase: ^3.0.8
  flutter_inappwebview: ^5.4.4+3
  flutter_secure_storage: ^5.0.2
  intl: ^0.17.0
  shared_preferences: ^2.0.13
  carousel_slider: ^4.0.0
  # video_player: ^2.4.10
  dio: ^4.0.6
  path_provider: ^2.0.9
  permission_handler: ^10.0.0
  gallery_saver: ^2.3.2
  # firebase_core: ^1.17.1
  video_thumbnail: ^0.5.0
  image: ^3.1.3
  flutter_image_compress: ^1.1.0
  image_cropper: ^2.0.3
  infinite_scroll_pagination: ^3.1.0
  url_launcher: ^6.0.20
  image_gallery_saver: ^1.7.1
  flutter_video_info: ^1.2.0
  clipboard: ^0.1.3
  timezone: ^0.8.0
  # firebase_crashlytics: ^2.8.1
  share_plus:
  intl_phone_number_input: ^0.7.1
  flutter_automation: 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
  #  - images/a_dot_ham.jpeg
  

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
